### PR TITLE
add a way to provide imported functions during relocation

### PR DESCRIPTION
**Pull request by Geal**
hello! I'm currently playing around with wasmtime, I needed this, let me know if it can be useful :)

### CODE REVIEW

**Comment by jrakow** [comment]
I was looking just at this on the weekend.

Can we make the import resolving allocation free?
For example, the user could supply a `Fn(&str) -> isize` (or `Fn(&str, &str) -> isize` with the module name`).

**Comment by sunfishcode** [comment]
Hi! Yes, we do need something like this. Would it work to pass the HashMap into `compile_and_link_module` rather than making `relocate` public?

@jrakow The import resolution uses the HashMap in a readonly way, so it doesn't so any allocation itself, so I think it's ok as is. That said, I could be convinced that passing in a closure is more general than passing in a HashMap :-).

**Comment by jrakow** [comment]
But a nonempty `HashMap` is always an allocation.
I was thinking of the static case, where you have a stable API and embed Wasm.
Ideally, it would only be big match statement in this case.

**Comment by sunfishcode** [comment]
@jrakow That's a good point. @Geal, would it work for you to make this a closure instead? For the HashMap use case, it seems like you could just do a HashMap lookup in the closure, but then users that don't have a HashMap could do other things.

**Comment by Geal** [comment]
@jrakow @sunfishcode I just pushed a new version that takes a closure as argument. It looks cleaner that way and I can still use a hashmap in the closure

**Comment by Geal** [comment]
I also removed `relocate` from the public API

**Comment by sunfishcode** [comment]
Thanks! This looks like a good step forward.

**Pull request merged**
