### PR TITLE
Merge wasi-common into wasmtime

### PR DESCRIPTION
**Pull request by kubkon**
This commit merges [CraneStation/wasi-common] repo as a subdir of this repo while preserving **all** of git history. There is an initiative to pull `wasi-common` into [CraneStation/wasmtime], and [CraneStation/wasmtime] becoming a monorepo. This came about for several reasons with a common theme of convenience, namely, having a monorepo:
1. cleans up the problem of dependencies (as we have seen first hand with dependabot enabled, it can cause some grief)
2. completely removes the problem of syncing the closely dependent repos (e.g., updating `wasi-common` with say a bugfix generally implies creating a "sync" commit for pulling in the changes into the "parent" repo, in this case, `wasmtime`)
3. mainly for the two reasons above, makes publishing to crates.io easier
4. hopefully streamlines the process of getting the community involved in contributing to `wasi-common` as now everything is in one place

[CraneStation/wasi-common]: https://github.com/CraneStation/wasi-common
[CraneStation/wasmtime]: https://github.com/CraneStation/wasmtime

---
cc @acfoltzer @pchickey @marmistrz @ibaryshnikov

Here are the things I'd really like your input on guys:
1. Should we merge this using a merge, rebase or squash commit strategy? I think ideally I would love to see it a rebase so that all contributors and their contributions are properly preserved. However, this might make it somewhat awkward for the existing PRs to sync up with this PR (merge strategy as an update should work for them though, so I guess we should be fine all in all).
2. So far, I've kept `wasmtime-wasi` and `wasi-common` separate, but I can see them becoming one. Question is, do we want that to happen, or should we keep them as separate crates? Also, keeping `wasi-common` separate, at least for now, preserves the crates.io history.

### CODE REVIEW

**Comment by kubkon** [comment]
Except for the `Rustfmt` job, I'm really confused as to why the WASI misc tests actually fail with this setup, and the worst thing is, I cannot seem to be able to reproduce the issues on either linux or macOS.

**Comment by marmistrz** [comment]
A couple of remarks:
* can we change the #no PR references to be PR URLs instead? Otherwise, the links will be completely broken.
* we definitely want to preserve the history, so either merge or rebase

**Comment by kubkon** [comment]
> can we change the #no PR references to be PR URLs instead? Otherwise, the links will be completely broken.

Agreed, but do you have any idea how to do that? Since the histories of the two repos are in fact unrelated, it’s quite difficult to navigate through them.

> we definitely want to preserve the history, so either merge or rebase

Agreed!

**Comment by marmistrz** [comment]
> Agreed, but do you have any idea how to do that? Since the histories of the two repos are in fact unrelated, it’s quite difficult to navigate through them.

We could just replace every #no to https://github.com/CraneStation/wasi-common/pull/no, so that the _pointers remain valid_ :)

**Comment by kubkon** [comment]
> We could just replace every #no to https://github.com/CraneStation/wasi-common/pull/no, so that the pointers remain valid :)

OK, I guess didn’t make myself clear last time. Traversing the commits in this PR, since we are merging two unrelated histories, makes targeting specific commits from this PR quite troublesome. For instance, `git rebase -i HEAD~5` would likely include a mix of commits from this branch and the master branch. So I cannot see an easy way to do this. If you have some ideas for this, then please do let me know.

**Comment by pchickey** [comment]
Over in Lucet we need to depend on `wasi-common` without pulling in the `wasmtime-wasi` bits. So, I'd prefer if those remain two separate crates.

Aside from that, I'm happy for this to get merged into the wasmtime repo in whatever manner works for everyone. Thanks for putting the work into this!

**Comment by acfoltzer** [comment]
This looks great to me! My main concern with the merging strategy is that `git blame` still works, even if I have to skip over a merge commit to get to the previous history.

**Comment by sunfishcode** [comment]
@kubkon I can reproduce the failures on linux by redirecting stdin, by adding "< /dev/null" to the cargo test line: `cargo test --features wasi-common/wasm_tests --all --exclude lightbeam --exclude wasmtime-wasi-c --exclude wasmtime-py -- --nocapture < /dev/null`.

**Comment by kubkon** [comment]
> Looks great to me, and agreed that keeping the history here is good too!
> 
> I'll see if I can help out with CI failures.

Thanks @alexcrichton!

**Comment by alexcrichton** [comment]
Ok I've pushed up a commit which I believe should fix the `poll_oneoff` test by guaranteeing that stdin is always set to an unreadable pipe locally within each test. It involved some refactoring here and there, so review would be appreciated!

**Comment by marmistrz** [comment]
Why thiserror + anyhow instead of failure?

**Comment by kubkon** [comment]
> Why thiserror + anyhow instead of failure?

That's the general direction we're heading in `wasmtime` since `thiserror` and `anyhow` re-use `std::error::Error` trait unlike `failure` which adds certain benefits as discussed in #436.

**Comment by kubkon** [comment]
Ok, I've now fixed `fd_readdir` on macOS/BSD, so the CI should pass all stages now :-)

**Comment by kubkon** [comment]
> Ok I've pushed up a commit which I believe should fix the `poll_oneoff` test by guaranteeing that stdin is always set to an unreadable pipe locally within each test. It involved some refactoring here and there, so review would be appreciated!

Your changes look great to me! Thanks!

**Comment by sunfishcode** [comment]
This is great!

As an aside, it will still be valuable to think of wasi-common as being relatively independent, and possibly something that we'll want to split out into its own repo again some day. But right now, having a single repo will make a lot of the work we're doing right now much easier.

**Pull request merged**
