### PR TITLE
Fix borrow scope for store in `WrappedCallable` impl for `WasmtimeFn`.

### LINKED ISSUE #365: Panic when reentering `wasm_func_call` from C API.
## Repro

With the following WASM module:

```wat
(module
  (type $t0 (func (result i32 i32)))
  (import "" "get" (func $.get (type $t0)))
  (func $add (result i32)
    call $.get
    i32.add
  )
  (export "add" (func $add))
  (func $a (result i32)
    i32.const 1
  )
  (export "a" (func $a))
  (func $b (result i32)
    i32.const 2
  )
  (export "b" (func $b))
)
```

Define an import for `get` that calls exported functions `a` and `b` on the instance (here is an example of doing so from a [prototype C# binding for Wasmtime](https://github.com/peterhuene/wasmtime.net)):

```c#
class Host : Wasmtime.Host
{
    [Import("get")]
    public (int, int) Get()
    {
        var instance = (dynamic)Instance;
        return (instance.a(), instance.b());
    }
}

class Program
{
    static void Main(string[] args)
    {
        using (var engine = new Engine())
        {
            using (var store = engine.CreateStore())
            {
                using (var module = store.CreateModule("test.wasm"))
                {
                    using (dynamic instance = module.Instantiate<Host>())
                    {
                        Console.WriteLine($"Function returned: {instance.add()}.");
                    }
                }
            }
        }
    }
}
```

## Expected Result

The program should output:

```
Function returned: 3.
```

## Actual Result

The program panics:

```
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1084:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: core::result::Result<T,E>::expect
   8: core::cell::RefCell<T>::borrow_mut
   9: <wasmtime_api::callable::WasmtimeFn as wasmtime_api::callable::WrappedCallable>::call
  10: wasmtime_api::externals::Func::call
  11: wasm_func_call
```

## Additional Information

The problem appears to be the [scope of the borrow for `store`](https://github.com/CraneStation/wasmtime/blob/master/wasmtime-api/src/callable.rs#L59), which remains borrowed across the call to `wasmtime_call_trampoline`.  This prevents any imported function from calling an exported function.

### PR DESCRIPTION
**Pull request by peterhuene**
This PR fixes the borrow scope of `store` in the `WrappedCallable` impl of 
`WasmTimeFn` such that it does not remain borrowed across the call to `wasmtime_call_trampoline`.  By limiting the scope of the borrow, the implementation can be reentered if an exported function calls an imported function, which in turn calls another exported function.

Fixes #365.

### CODE REVIEW

**Comment by sunfishcode** [comment]
This looks good; would it be feasible to convert your example from #365 into a testcase? wasmtime-api/examples/gcd.rs may be useful as a starting point.

**Comment by peterhuene** [comment]
I didn't see formal tests for the API crate yet.  Should I add a unit test or an example test case?

**Comment by sunfishcode** [comment]
I think it makes sense to add a `tests` directory, and add this as a test there.

**Comment by peterhuene** [comment]
@sunfishcode I've amended the commit with a test case.

**Comment by peterhuene** [comment]
@sunfishcode @yurydelendik It appears that there's a calling convention mismatch for the import in the new test case on Windows. Is there something I should be doing in the Rust API or is this a current limitation?

**Comment by yurydelendik** [comment]
> It appears that there's a calling convention mismatch for the import in the new test case on Windows. Is there something I should be doing in the Rust API or is this a current limitation?

Let's disable tests on Windows, so it will not block landing of this PR -- I'll look into that calling convention problem shortly.

**Comment by peterhuene** [comment]
Should I file a new issue to track the panic?

**Comment by peterhuene** [comment]
Filed as https://github.com/CraneStation/wasmtime/issues/378.

**Comment by peterhuene** [comment]
`cache::tests::test_write_read_cache` from `wasmtime-environ` is failing on Windows and appears unrelated to these changes.  Are there any known issues with this test?

**Comment by sunfishcode** [comment]
@Mrowqa Would you mind taking a look at this test failure?

**Comment by peterhuene** [comment]
@Mrowqa the `cache::tests::test_write_read_cache` failure is from this build: https://dev.azure.com/CraneStation/Wasmtime/_build/results?buildId=1064.

**Comment by Mrowqa** [comment]
@peterhuene I can't reproduce the CI failure. I have updated the Rust version in the meantime, though. Since the test changed in the meantime, my suggestion was to rebase your PR onto master, but I can see you already did that when I was writing this comment 😃  . Other weird thing is the stack trace didn't make sense. It pointed to an empty line.

**Comment by peterhuene** [comment]
@Mrowqa thanks for looking into it.  I'll keep an eye out in case it fails again.

**Comment by Mrowqa** [comment]
Looks like everything works. The formatting problem is within lightbeam. I have already opened an PR there https://github.com/CraneStation/lightbeam/pull/28.

**Comment by sunfishcode** [comment]
Thanks!

**Pull request merged**
