### PR TITLE
Add test_environ_translate

### PR DESCRIPTION
**Pull request by frehberg**
Initial layout to add utests to wasmtime. More tests shall follow testing different aspects. The naming scheme of the input-files such as  'filetests/rs2wasm-add-func.wasm' shall refer to the toolchain producing the wasm-output under test, namely emscripten, clang, rustc.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks for working on tests! I think my one comment at this point is that I'd like to use "wat" files rather than "wasm" files, and do something like what `handle_module` in this file does using `wabt::wat2wasm`.

**Comment by frehberg** [comment]
I agree, the wat-format is easier to check :) The test will now read the wat-file and converting to wasm via function wabt::wat2wasm. The wabt-crate will be pulled in only for testing. Please let me know, should wabt::wat2wasm be used in main-function as well, instead of command line tool?

**Comment by sunfishcode** [comment]
Yes, I think it'd be good for the main function to use wabt::wat2wasm too. We wouldn't want it as a dependency in the lib/* crates, but it's fine in the top-level crate.

**Comment by frehberg** [comment]
I would like to split it into two patches, please could this be merged, than I will fix patch #29

**Pull request merged**
