### PR TITLE
Update cranelift for full multi-value

### PR DESCRIPTION
**Pull request by fitzgen**
This is ready for review, but landing it still relies on a few (largely trivial or orthogonal) things happening first:

* [x] Cranelift merging https://github.com/CraneStation/cranelift/pull/1147

* [x] A new cranelift release that includes that PR

* [x] Removing the "TEMP" commit and replacing it with a version bump on our cranelift dependencies

### CODE REVIEW

**Comment by fitzgen** [comment]
(CI is, of course, going to fail because of the "TEMP" commit that makes us use a local cranelift)

**Comment by yurydelendik** [comment]
I added https://github.com/CraneStation/wasmtime/pull/466/commits/2db956faab02ea16739e8f4aa38521390d1c6b55 to bypass failing on windows multi test, can you check if it will be fixed by your patch?

- [ ] enable multi.rs example test on windows ?

**Comment by fitzgen** [comment]
> I added [2db956f](https://github.com/CraneStation/wasmtime/commit/2db956faab02ea16739e8f4aa38521390d1c6b55) to bypass failing on windows multi test, can you check if it will be fixed by your patch?

I added a commit to enable it on windows, but I don't have a windows setup to test locally against right now.

**Comment by peterhuene** [comment]
You'll need #462 merged to enable the multivalue tests on Windows.  I'm going to run the tests now with the unwind changes to see if they pass.

**Comment by fitzgen** [comment]
> You'll need #462 merged to enable the multivalue tests on Windows. I'm going to run the tests now with the unwind changes to see if they pass.

Thanks for the heads up.

I think there is a bug on windows with the way we determine the number of return registers required for a signature in `cranelift-codegen`:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `18446744073709551615`,
 right: `128`', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\cranelift-codegen-0.49.0\src\isa\x86\abi.rs:150:13
```

cc @bnjbvr: I think I will switch `num_return_registers_required` to do the clone and count, instead of trying to simulate argument assigning with a fake set of registers. As you suspected, it is a little fragile :( Sound good?

**Comment by peterhuene** [comment]
I'm seeing the same assertion failure with the unwind changes.

These tests are the only ones failing on Windows for me:

```
    Cranelift::multi_value::br
    Cranelift::multi_value::call
    Cranelift::multi_value::call_indirect
```

The rest are green.

**Comment by fitzgen** [comment]
Ok, I have a fix for the `cranelift-codegen` bug over in https://github.com/CraneStation/cranelift/pull/1213

So now we just need:

* [ ] https://github.com/CraneStation/cranelift/pull/1213 to land
* [ ] a new cranelift release with that fix
* [ ] to remove the new TEMP commit that uses patches the deps to point to that branch

**Comment by sunfishcode** [comment]
A new cranelift, 0.50, is now up!

**Pull request merged**
